quarkus.grpc.clients.riesgos.host=localhost
quarkus.grpc.clients.riesgos.port=9001

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=bda
quarkus.datasource.password=bda
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/bda_db

quarkus.hibernate-orm.schema-management.strategy=update

quarkus.http.port=8082

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,OPTIONS
quarkus.http.cors.headers=Content-Type,Accept
